name: no_truco
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth:
  firebase_core: ^3.0.0
  google_sign_in: ^6.1.5
  cupertino_icons: ^1.0.2
  page_transition: "^2.0.5"
  smooth_page_indicator: ^1.1.0
  flutter_animate: ^4.2.0+1
  provider: ^6.0.5
  flutter_signin_button: ^2.0.0
  google_fonts: ^6.2.1
  cloud_firestore: ^5.0.0
  uuid: ^4.0.0
  equatable: ^2.0.5
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_app_name: ^0.1.1

flutter_app_name:
  name: "NoTruco"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Conthrax
      fonts:
        - asset: assets\fonts\conthrax.ttf

    - family: Montserrat
      fonts:
        - asset: assets\fonts\Montserrat\Montserrat-Thin.ttf
          weight: 100
        - asset: assets\fonts\Montserrat\Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets\fonts\Montserrat\Montserrat-Light.ttf
          weight: 300
        - asset: assets\fonts\Montserrat\Montserrat-Regular.ttf
          weight: 400
        - asset: assets\fonts\Montserrat\Montserrat-Medium.ttf
          weight: 500
        - asset: assets\fonts\Montserrat\Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets\fonts\Montserrat\Montserrat-Bold.ttf
          weight: 700
        - asset: assets\fonts\Montserrat\Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets\fonts\Montserrat\Montserrat-Black.ttf
          weight: 900