// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCznOY9k25vV62nbH8XcS5AfISLytbRi50',
    appId: '1:945480577107:web:0f1b6f3fea21b27d6816a6',
    messagingSenderId: '945480577107',
    projectId: 'notruco',
    authDomain: 'notruco.firebaseapp.com',
    storageBucket: 'notruco.appspot.com',
    measurementId: 'G-V5BMNGK6VM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY0VTCC6UffYQmQ_QPhimjRCiLtqpBur4',
    appId: '1:945480577107:android:4108b9a84f8ede926816a6',
    messagingSenderId: '945480577107',
    projectId: 'notruco',
    storageBucket: 'notruco.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1Md2iDw_u_eV4WXvtRINRMOXDBi63yIk',
    appId: '1:945480577107:ios:d26cbd048b2903556816a6',
    messagingSenderId: '945480577107',
    projectId: 'notruco',
    storageBucket: 'notruco.appspot.com',
    iosClientId: '945480577107-gg3r36kpjhaafeg5mupa3a5isbjt7h71.apps.googleusercontent.com',
    iosBundleId: 'com.example.noTruco',
  );
}
